DoctorOffice/Models/Patient.cs
using System.Collections.Generic;

namespace DoctorOffice.Models
{
  public class Patient
  {
    public Patient()
    {
      this.Doctors = new HashSet<DoctorPatient>();
    }

    public int PatientId { get; set; }
    public string Name { get; set; }
    public string Birthdate { get; set; }

    public ICollection<DoctorPatient> Doctors { get; }
  }
}

DoctorOffice/Controllers/DoctorsController.cs
using Microsoft.AspNetCore.Mvc;
using DoctorOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DoctorOffice.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly DoctorOfficeContext _db;

    public DoctorsController(DoctorOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Doctor> model = _db.Doctors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Doctor doctor, int SpecialtyId)
    {
      _db.Doctors.Add(doctor);
      if (SpecialtyId != 0)
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() { SpecialtyId = SpecialtyId, DoctorId = doctor.DoctorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDoctor = _db.Doctors
      .Include(doctor => doctor.Patients)
      .ThenInclude(join => join.Patient)
      .Include(doctor => doctor.Specialties)
      .ThenInclude(join => join.Specialty)
      .FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    public ActionResult Edit(int id)
    {
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult Edit(Doctor doctor, int SpecialtyId)
    {
      if (SpecialtyId != 0)
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() { SpecialtyId = SpecialtyId, DoctorId = doctor.DoctorId });
      }
      _db.Entry(doctor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      _db.Doctors.Remove(thisDoctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

DoctorOffice/Controllers/PatientsController.cs
using Microsoft.AspNetCore.Mvc;
using DoctorOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DoctorOffice.Controllers
{
  public class PatientsController : Controller
  {
    private readonly DoctorOfficeContext _db;

    public PatientsController(DoctorOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Patients.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Patient patient, int DoctorId)
    {
      _db.Patients.Add(patient);
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisPatient = _db.Patients
      .Include(patient => patient.Doctors)
      .ThenInclude(join => join.Doctor)
      .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    public ActionResult Edit(int id, int specialtyId)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      // ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      List<string> doctorList = new List<string>(); 
      var model = _db.Doctors;
      if (specialtyId == model.Doctors.Specialties.SpecialtyId)
      {
        doctorList.Add(model.Name);
        ViewBag.DoctorId =  new SelectList(doctorList, "DoctorId", "Name");
      }
      return View(thisPatient);
    }
      // return View(thisPatient);
    // }

    [HttpPost]
    public ActionResult Edit(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.Entry(patient).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddDoctor(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisPatient);
    }
    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteCateogry(int joinId)
    {
      var joinEntry = _db.DoctorPatient.FirstOrDefault(entry => entry.DoctorPatientId == joinId);
      _db.DoctorPatient.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
        public ActionResult Delete(int id)
        {
          var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
          return View(thisPatient);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
          var thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
          _db.Patients.Remove(thisPatient);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
  }
}

DoctorOffice/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<h4>Add a new task</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    @Html.Label("Select Doctor")
    @Html.DropDownList("DoctorId")

    <input type="submit" value="Add new Patient" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Patients", "Index")</p>

DoctorOffice/Views/Patients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

DoctorOffice/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
}
@model DoctorOffice.Models.Patient
<h2>Patient Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.Doctors.Count ==0)
{
  <p>This Patient does not belong to any Doctors</p>
}
else
{
  <h4>Doctors the Patient belongs to:</h4>
<ul>
  @foreach(var join in Model.Doctors)
  {
    <li>@join.Doctor.Name</li>
    @using (Html.BeginForm("DeleteDoctor", "Patients"))
    {
      @Html.Hidden("joinId", @join.DoctorPatientId)
      <input type="submit" value="Delete"/>
    }
  }
</ul>
}
<p>@Html.ActionLink("Add a Doctor", "AddDoctor", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Patient", "Edit", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Delete Patient", "Delete", new { id = Model.PatientId })</p>

DoctorOffice/Views/Patients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DoctorOffice.Models.Patient

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm("Index", "Doctors", FormMethod.Get))
{
    @Html.HiddenFor(model => model.PatientId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.Label("Select Specialty")
    @Html.DropDownList("SpecialtyId")

    @Html.Label("Select Doctor")
    @Html.DropDownList("DoctorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

  @* @using (Html.BeginForm("Index", "Artists", FormMethod.Get))
  {
    <p>Search Artist: @Html.TextBox("firstName")</p>
    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
  }  *@

@* public ActionResult Index(string firstName = "")
    {
      var model = _db.DoctorSpecialty;
      if (!string.IsNullOrEmpty(firstName))
      {
        return View(model.AsQueryable().Where(doctor => doctor.Specialties.Contains(SpecialtyId)).ToList());
      }
      return View(model.ToList());
    } *@

DoctorOffice/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorOffice.Models;
@model List<DoctorOffice.Models.Patient>;

<h1>Patients</h1>

@if (@Model.Count == 0)
{
  <h3>No Patients have been added yet!</h3>
} 

@foreach (Patient patient in Model)
{
  <li>@Html.ActionLink($"{patient.Name}", "Details", new { id = patient.PatientId })</li>
}

<p>@Html.ActionLink("Add new Patient", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>